config/routes.rb
Rails.application.routes.draw do
  
  root to: "events#index"
  get "events/search", to: "events#search", as: "events_search"
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks",
    confirmations: "users/confirmations",
    passwords: "users/passwords"
  }

  resources :events do
    collection do
      get :search
    end
  end

  resources :users, only: [:show, :edit, :update] do
    get :favourite
    get :my_events
  end

  resources :supports, only: [:new, :create]
  namespace :admin do
    resources :supports, only: [:index, :show, :update]
    resources :users do
      member do
        patch :block
        patch :unblock
      end
    end
    resources :events do
      resources :reviews, only: [:index, :edit, :update, :destroy], module: :events
    end
  end
  
  resources :favourites, only: [:create, :destroy]

  #resources :events, only: [:index, :show]

  #resources :carts, only: [:show]

  get 'checkouts/index/:id' => 'checkouts#index', as: 'checkouts_index'
  get 'checkouts/show'
  get 'checkouts/new'

  post 'checkouts/create' => "checkouts#create", as: "checkouts_create"
  get 'checkouts/success' => "checkouts#success", as: "checkouts_success"
  get 'checkouts/cancel' => "checkouts#cancel", as: "checkouts_cancel"

  get 'carts/show'
  
  get 'carts/:cart_id' => "carts#show", as: "cart"
  get 'cart_items/:cart_item_id' => "cart_items#show", as: "cart_item"
  
  post 'cart_items/:cart_item_id/increase' => "cart_items#increment_number", as: "cart_item_increase"
  post 'cart_items/:cart_item_id/decrease' => "cart_items#decrease_number", as: "cart_item_decrease"
  post 'cart_items' => "cart_items#create"

  delete 'carts/:cart_id' => "carts#destroy"
  delete 'cart_items/:cart_item_id' => "cart_items#destroy", as: "cart_item_delete"

  # ADMIN

  namespace :admin do
    get 'dashboard', to: 'dashboard#show'
    resources :users
    resources :events
  end

  resources :reviews, only: [:new, :create, :edit, :update, :destroy]

  resources :tickets, only: [:index]
  resources :tickets do
    member do
      get :download_pdf
    end
  end
  


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  
end

app/models/user.rb
class User < ApplicationRecord

  has_many :events
  has_many :reviews, dependent: :destroy
  
  has_many :favourites, dependent: :destroy
  has_many :favourite_events, through: :favourites, source: :event, dependent: :destroy
  has_many :checkouts
  has_many :tickets

  has_many :supports, dependent: :destroy

  after_create :set_stripe_customer_id

  # enum :role, user: 0, event_planner: 1, admin: 2

  has_one_attached :profile_pic

  validates :bio, absence: true, unless: :event_planner?

  def user?
    self.role == 0
  end

  def event_planner?
    self.role == 1
  end

  def admin?
    self.role == 2
  end

  def favourited?(event)
    favourite_events.include?(event)
  end

  def blocked?
    blocked
  end

  def active_for_authentication?
    super && !blocked?
  end

  def inactive_message
    blocked? ? "Il tuo account è stato bloccato." : super
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :timeoutable, :lockable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(auth)
    where(uid: auth.uid, provider: auth.provider).first_or_create do |user|
      user.provider = auth.provider
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.city = auth.info.city
      user.phone_number = auth.info.phone_number
      user.skip_confirmation!
    end
  end

  private

  def set_stripe_customer_id 
    address_obj_json = { 
      city: self.city, 
      country: 'IT'
    }
    customer = Stripe::Customer.create(
      email: self.email,
      address: address_obj_json,
      phone: self.phone_number,
      #name: self.first_name + ' ' + self.last_name
    )
    update(stripe_customer_id: customer.id)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin_role

  def index
    @users = User.all
    @query = params[:query]
    @role = params[:role]
    if @query.present?
      @users = @users.where("first_name LIKE ? OR last_name LIKE ? OR email LIKE ?", "%#{@query}%", "%#{@query}%", "%#{@query}%")
    end
    if @role.present?
      role_mapping = {
        "User" => 0,
        "Event Planner" => 1,
        "Admin" => 2
      }
      role_value = role_mapping[@role]
      @users = @users.where(role: role_value) if role_value.present?
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.confirmed_at = Time.now
    if @user.save
      redirect_to admin_users_path, notice: 'Utente creato con successo.'
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    if @user.update(user_params)
      UserMailer.account_updated(@user).deliver_now!
      redirect_to admin_users_path, notice: 'Utente aggiornato con successo.'
    else
      Rails.logger.debug @user.errors.full_messages.inspect
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    UserMailer.account_destroyed(@user).deliver_now!

    redirect_to admin_users_path, notice: 'Utente eliminato con successo.'
  end

  def block
    user = User.find(params[:id])
    user.update(blocked: true)

    UserMailer.account_blocked(user).deliver_now!

    redirect_to admin_users_path, notice: "L'utente #{user.email} è stato bloccato."
  end

  def unblock
    user = User.find(params[:id])
    user.update(blocked: false)
    redirect_to admin_users_path, notice: "L'utente #{user.email} è stato sbloccato."
  end

  private

  def check_admin_role
    redirect_to root_path, alert: "Accesso non autorizzato" unless current_user.role == 2
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :role, :phone_number, :city, :bio, :blocked)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    new_user_session_path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  def google_oauth2
    user = User.from_omniauth(auth)
    if user.present?
      sign_out_all_scopes
      flash[:success] = t "devise.omniauth_callbacks.success", kind: "Google"
      sign_in_and_redirect user, event: :authentication
    else
      flash[:alert] = t "devise.omniauth_callbacks.failure", kind: "Google", reason: "#{auth.info.email} is not authorized."
      redirect_to new_user_session_path
    end
  end

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  protected

  def after_omniauth_failure_path_for(_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    @user = current_user
    if @user.role.nil?
      flash[:alert] = "Inserisci il tuo ruolo per continuare."
      edit_user_path(@user.id)
    else
      stored_location_for(resource_or_scope) || root_path
    end
  end

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  private
  def auth
    @auth ||= request.env["omniauth.auth"]
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  def update
    super do |user|
      if user.errors.empty?
        sign_out(user)
        flash[:notice] = "La tua password è stata cambiata con successo. Effettua nuovamente il login."
        return redirect_to new_user_session_path
      end
    end
  end

  protected

  ## The path used after resetting password
  #def after_resetting_password_path_for(resource)
  #  new_session_path(resource)
  #end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    new_user_password_path
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  #def update_resource(resource, params)
  #  if resource.provider == "google_oauth2"
  #    params.delete("current_password")
  #    resource.password = params["password"]
  #    resource.update_without_password(params)
  #  else
  #    resource.update_with_password(params)
  #  end
  #end

  def update_resource(resource, params)
    if !params['current_passwword'].present?
      params.delete('current_password')
      resource.password = params['password']
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :role, :city, :phone_number, :image_url)
  end

  def create
    super do |resource|
      resource.role = role_from_params
      resource.save
    end
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:profile_pic])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    if resource.provider == "google_oauth2"
      root_path
    else
      new_user_confirmation_path
    end
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    new_user_confirmation_path
  end

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :role, :city, :phone_number, :image_url)
  end

  def role_from_params
    return 0 if params[:user][:role].include?('0')
    return 1 if params[:user][:role].include?('1')
    return 2 if ["zarola.admin@gmail.com", "paula.admin@gmail.com", "pesce.admin@gmail.com"].include?(params[:user][:email])
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  # skip_before_action :require_no_authentication, only: [:new]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    session[:cart_id] = nil
    super
  end

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end

  #def after_sign_in_path_for(resource_or_scope)
  #  stored_location_for(resource_or_scope) || root_path
  #end

  def after_sign_in_path_for(resource)
    if resource.role == 2 
      admin_dashboard_path 
    else
      root_path 
    end
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def my_events
    @events = Event.where(user_id: current_user.id)
    @query = params[:query]
    @city = params[:city]
    @category = params[:category]
    if @query.present?
      @events = @events.where("title LIKE ? OR description LIKE ?", "%#{@query}%", "%#{@query}%")
    end

    if @city.present?
      @events = @events.where("city LIKE ?", "%#{@city}%")
    end

    if @category.present?
      @events = @events.where("category LIKE ?", "%#{@category}%")
    end
    render 'users/my_events'
  end

  def show
    @user = User.find(params[:id])
    @tickets = @user.tickets.includes(:event)
    
    if @user.role == 0
      @upcoming_events = @tickets
        .map(&:event)
        .compact
        .select { |event| event.status == 'upcoming' }
        .sort_by(&:start_datetime)
    
      @terminated_events = @tickets
        .map(&:event)
        .compact
        .select { |event| event.status == 'terminated' }
        .sort_by(&:start_datetime)
    else
      @upcoming_events = @user.events.where(status: 'upcoming')
      @terminated_events = @user.events.where(status:'terminated')
    end
      
    render 'users/show'
  end  

  def edit
    @user = User.find(params[:id])
    # render 'users/edit'
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to @user, notice: "Profilo aggiornato con successo"
    else
      render :edit
    end
  end

  def destroy

  end

  def favourite
    authorize! :read, Favourite
    @user = current_user
    @favourites = @user.favourite_events
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :role, :city, :phone_number, :profile_pic, :bio)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<!-- <h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p> -->

<% if @user.role.present? && @user.first_name.present? && @user.last_name.present? %>
  <%= render "devise/shared/navbar" %>
<% end %>

<div class="page-info">
  <div class="account-settings-container">
    <% if @user.role.present? && @user.first_name.present? && @user.last_name.present? %>
      <div class="sidebar">
        <h2>Impostazioni Account</h2>
        <ul>
          <li id="selected-w"><%= link_to "Modifica Profilo", edit_user_path(current_user) %></li>
          <li><%= link_to "Modifica Password", edit_user_registration_path %></li>
        </ul>
      </div>
    <% end %>
    <div class="settings-content">
      <h2>Modifica Account</h2>
      <hr>
      <%= form_with model: @user, url: user_path(@user), method: :patch do |f| %>
        <div class="form-group">
          <%= f.label :first_name, "Nome" %>
          <%= f.text_field :first_name, placeholder: "First name", class: "form-control", required: true %>
        </div>

        <div class="form-group">
          <%= f.label :last_name, "Cognome" %>
          <%= f.text_field :last_name, placeholder: "Last name", class: "form-control", required: true %>
        </div>

        <div class="form-group">
          <%= f.label :city, "Città" %>
          <%= f.text_field :city, placeholder: "Città", class: "form-control"  %>
        </div>

        <div class="form-group">
          <%= f.label :phone_number, "Numero di Telefono" %>
          <%= f.text_field :phone_number, placeholder: "Numero di Telefono", class: "form-control"  %>
        </div>

        <div class="form-group">
          <%= f.label :profile_pic, "Immagine Profilo" %><br>
          <%= f.file_field :profile_pic %>
        </div>

        <% if @current_user.role.nil? %>
          <div class="form-group">
            <%= f.label :role, "Seleziona il tuo ruolo" %><br>

            <div class="form-check">
              <%= f.radio_button :role, '0', checked: @user.role == '0', class: "form-check-input", id: "user", required: true %>
              <%= f.label :role, "User", class: "form-check-label", for: "user" %>
            </div>

            <div class="form-check">
              <%= f.radio_button :role, '1', checked: @user.role == '1', class: "form-check-input", id: "eventplanner", required: true %>
              <%= f.label :role, "Eventplanner", class: "form-check-label", for: "eventplanner" %>
            </div>

          </div>
        <% end %>
        
        <div class="form-action">
          <%= f.submit "Salva modifiche", class: "save-btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% if @user.role.present? && @user.first_name.present? && @user.last_name.present? %>
  <%= render "devise/shared/footer" %>
<% end %>

app/views/users/favourite.html.erb
<%= render "devise/shared/navbar" %>
<div class= "page">
    <div class="wrap-title">
        <%= link_to '#', onclick: "history.back(); return false;" do %>
            <i class="fa-solid fa-arrow-left"></i>
        <% end %>
        <h1>Eventi Preferiti</h1>
    </div>
    <div class= "favourite-page">
        <div class="events-grid">
            <% if @favourites == [] %>
                <p>Nessun evento preferito.</p>
            <% else %>
                <% @favourites.each do |event|%>
                    <%= link_to event_path(event.id), class: "event-card-link" do %>
                        <div class="event-card">
                            <div class="event-design">
                                <%= image_tag(event_image(event), alt: "Event Image", class: "event-image") %>
                            </div>

                            <div class="event-frame">

                                <div class="event-date">
                                    <span class="month"><%= event.start_datetime.strftime("%b")%></span>
                                    <span class="day"><%= event.start_datetime.day%></span>
                                </div>

                                <div class="event-details">
                                    <h3 class="event-title"><%= event.title %></h3>
                                    <p class="event-location"><%= event.address + ", " +event.city+", "+event.country%></p>
                                    <p class="event-time"><%= event.start_datetime.strftime("%I:%M %p")%></p>
                                    </div>
                            </div>
                            
                        </div>
                    <% end %>
                <% end %>
            <% end %>
        </div>
    </div>
    <%= render "devise/shared/footer" %>
</div>

app/views/users/my_events.html.erb
<%= render "devise/shared/navbar" %>
<div class= "page">
    <div class= "wrap-title">
        <%= link_to root_path do %>
            <i class="fa-solid fa-arrow-left"></i>
        <% end %>
        <h1> I Miei Eventi </h1>
    </div>

    <div class="search-area">
        <div class="search-section">
        <div class="search-bar">
            <%= form_with url: user_my_events_path, method: :get, local: true, class: "search-bar" do %>
            <div class="search-input">
                <%= text_field_tag :query, params[:query], placeholder: "Cerca...", class: "search-field" %>
            </div>

            <div class="search-divider"></div>

            <div class="search-dropdown">
                <%= select_tag :city, options_for_select([['Città...', ''], 'Roma', 'Milano', 'Napoli', 'Torino', 'Firenze'], params[:city]), class: "city-dropdown" %>
            </div>

            <div class="search-divider"></div>

            <div class="search-dropdown">
                <%= select_tag :category, options_for_select([['Categoria...', ''], 'Musica', 'Food&Drinks', 'Comedy', 'Teatro', 'Sport', 'Hobby', 'Arte', 'Festa'], params[:category]), class: "city-dropdown" %>
            </div>

            <button type="submit" class="search-button">
                <i class="fas fa-search"></i>
            </button>
            <% end %>
        </div>
        </div>
    </div>

    <div class= "my_events-page">
        <div class="events-grid">
            <% if @events == [] %>
                <p>Non gestisci nessun evento.</p>
            <% else %>
                <% @events.each do |event|%>
                    <%= link_to event_path(event.id), class: "event-card-link" do %>
                        <div class="event-card">
                            <div class="event-design">
                                <%= image_tag(event_image(event), alt: "Event Image", class: "event-image") %>
                            </div>

                            <div class="event-frame">
                                <h3 class="event-title"><%= event.title %></h3>
                                <p class="event-location"><%= event.address+", "+event.city+", "+event.country %></p>
                                <div class="event-date">
                                    <span class="month"><%= event.start_datetime.strftime("%b") %></span>
                                    <span class="day"><%= event.start_datetime.strftime("%d") %></span>
                                </div>
                                <p class="event-time"><%= event.start_datetime.strftime("%H:%M") %></p>
                                <% if event.event_price == 0 || event.event_price == nil %>
                                    <p class="event-price">Gratis</p>
                                <% else %>
                                    <p class="event-price"><%= number_to_currency(event.event_price, unit: "€") %></p>
                                <% end %>
                                <div class="my-ev-btns">
                                    <%= link_to 'Modifica', edit_event_path(event.id), class: 'action-link edit-link' %>
                                    <%= button_to 'Elimina', event_path(event.id), method: :delete, data: { confirm: 'Sei sicuro?' }, class: 'action-link delete-link' %>
                                </div>
                                 
                            </div>
                        </div>
                    <% end %>
                <% end %>
            <% end %>

        </div>
    </div>
    <%= render "devise/shared/footer" %>
</div>

app/views/users/show.html.erb
<%= render "devise/shared/navbar" %>

<div class="page">
    <div class="banner">
        <div class="banner-content">
            <div class="info-profile">
                <% if @user.profile_pic.present? %>
                    <%= image_tag(@user.profile_pic, data: { action: "click->dropdown#toggle" } )%>
                <% else %>
                    <%= image_tag("default-avatar.png", data: { action: "click->dropdown#toggle" } )%>
                <% end %>
                <h1><%= @user.first_name + " " + @user.last_name %></h1>
            </div>
            <%= link_to edit_user_path(current_user) do %>
                <button class="edit-btn">Modifica</button>
            <% end %>
        </div>
    </div>
    <% if @user.role==1%>
        <div class="page-content">
        
            <div class="description">
                <h3>Descrizione</h3>
                <p>
                    <% if @user.bio.present? %>
                        <%= @user.bio %>
                    <% end %>
                </p>
            </div>
        
        </div>
    <% end %>

    <div class="events">
        <div class="choice">
            <h3 id="upcoming-toggle" class="events_current">Prossimi Eventi</h3>
            <h3 id="past-toggle" class="events_past">Eventi Passati</h3>
        </div>
        <div class="line"></div>

        <% if @upcoming_events.any? %>
            <div id="upcoming-events" class="events-list">
                <div class="events-grid">
                    <% @upcoming_events.each do |event| %>
                        <%= link_to event_path(event), class: "event-card-link" do %>
                            <div class="event-card">
                                <div class="event-design">
                                    <%= image_tag(event_image(event), alt: "Event Image", class: "event-image") %>
                                </div>
                                <div class="event-frame">
                                    <h3 class="event-title"><%= event.title %></h3>
                                    <p class="event-location"><%= event.address+", "+event.city+", "+event.country %></p>
                                    <div class="event-date">
                                        <span class="month"><%= event.start_datetime.strftime('%b') %></span>
                                        <span class="day"><%= event.start_datetime.strftime('%d') %></span>
                                    </div>
                                    <p class="event-time"><%= event.start_datetime.strftime('%I:%M %p') %></p>
                                    <p class="event-price"><%= event.event_price.present? ? event.event_price : "Free" %></p>
                                </div>
                            </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
        <% else %>
            <p>Nessun evento in programma.</p>
        <% end %>

        <% if @terminated_events.any? %>
            <div id="past-events" class="events-list" style="display: none;">
                <div class="events-grid">
                    <% @terminated_events.each do |event| %>
                        <%= link_to event_path(event), class: "event-card-link" do %>
                            <div class="event-card">
                                <div class="event-design">
                                    <%= image_tag(event_image(event), alt: "Event Image", class: "event-image") %>
                                </div>
                                <div class="event-frame">
                                    <h3 class="event-title"><%= event.title %></h3>
                                    <p class="event-location"><%= event.address+", "+event.city+", "+event.country %></p>
                                    <div class="event-date">
                                        <span class="month"><%= event.start_datetime.strftime('%b') %></span>
                                        <span class="day"><%= event.start_datetime.strftime('%d') %></span>
                                    </div>
                                    <p class="event-time"><%= event.start_datetime.strftime('%I:%M %p') %></p>
                                    <p class="event-price"><%= event.event_price.present? ? event.event_price : "Free" %></p>
                                </div>
                            </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
        <% else %>
            <p>Nessun evento passato.</p>
        <% end %>
    </div>
    
</div>


<script>
    document.getElementById("upcoming-toggle").addEventListener("click", function() {
        document.getElementById("upcoming-events").style.display = "block";
        document.getElementById("past-events").style.display = "none";
    });

    document.getElementById("past-toggle").addEventListener("click", function() {
        document.getElementById("past-events").style.display = "block";
        document.getElementById("upcoming-events").style.display = "none";
    });
</script>

<%= render "devise/shared/footer" %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>