config/routes.rb
Rails.application.routes.draw do
  
  root to: "events#index"
  get "events/search", to: "events#search", as: "events_search"
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks",
    confirmations: "users/confirmations",
    passwords: "users/passwords"
  }

  resources :events do
    collection do
      get :search
    end
  end

  resources :users, only: [:show, :edit, :update] do
    get :favourite
    get :my_events
  end

  resources :supports, only: [:new, :create]
  namespace :admin do
    resources :supports, only: [:index, :show, :update]
    resources :users do
      member do
        patch :block
        patch :unblock
      end
    end
    resources :events do
      resources :reviews, only: [:index, :edit, :update, :destroy], module: :events
    end
  end
  
  resources :favourites, only: [:create, :destroy]

  #resources :events, only: [:index, :show]

  #resources :carts, only: [:show]

  get 'checkouts/index/:id' => 'checkouts#index', as: 'checkouts_index'
  get 'checkouts/show'
  get 'checkouts/new'

  post 'checkouts/create' => "checkouts#create", as: "checkouts_create"
  get 'checkouts/success' => "checkouts#success", as: "checkouts_success"
  get 'checkouts/cancel' => "checkouts#cancel", as: "checkouts_cancel"

  get 'carts/show'
  
  get 'carts/:cart_id' => "carts#show", as: "cart"
  get 'cart_items/:cart_item_id' => "cart_items#show", as: "cart_item"
  
  post 'cart_items/:cart_item_id/increase' => "cart_items#increment_number", as: "cart_item_increase"
  post 'cart_items/:cart_item_id/decrease' => "cart_items#decrease_number", as: "cart_item_decrease"
  post 'cart_items' => "cart_items#create"

  delete 'carts/:cart_id' => "carts#destroy"
  delete 'cart_items/:cart_item_id' => "cart_items#destroy", as: "cart_item_delete"

  # ADMIN

  namespace :admin do
    get 'dashboard', to: 'dashboard#show'
    resources :users
    resources :events
  end

  resources :reviews, only: [:new, :create, :edit, :update, :destroy]

  resources :tickets, only: [:index]
  resources :tickets do
    member do
      get :download_pdf
    end
  end
  


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :events, through: :cart_items
  has_one :checkout

  # decrementa la disponibilità dell'evento quando viene aggiunto al carrello
  def decrease_availability
    self.cart_items.each do |cart_item|
      selected_quantity = cart_item.quantity
      cart_item.event.current_participants += selected_quantity
      cart_item.event.save
    end
  end

  # calcola il totale del carrello
  def sub_total
    sum = 0
    self.cart_items.each do |cart_elem|
      if !cart_elem.event.nil?
        sum += cart_elem.total_price
      end
    end
    return sum
  end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :checks_oauth_params

  load_and_authorize_resource #@current_cart

  def show
    @cart = @current_cart
  end

  def destroy
    session[:cart_id] = nil
    redirect_to root_path
  end

  private

  # controlla se i parametri dell'utente sono presenti (nome e cognome)
  def checks_oauth_params
    if @current_user.first_name.blank? || @current_user.last_name.blank?
      redirect_to edit_user_path(current_user)
      flash[:alert] = "Update your account with first name and last name."
    end
  end

end

app/views/carts/show.html.erb
<%= render "devise/shared/navbar" %>

<div class="cart-menu">
  
  <div class="sidebar">
    <h2>Acquisti</h2>
    <ul>
      <li><%= link_to "Carrello", cart_path(@current_cart)%></li>
      <li><%= link_to "I miei ordini", checkouts_index_path(current_user.id) %></li>
      <li><%= link_to "I miei biglietti", tickets_path(current_user.id) %></li>
    </ul>
  </div>

  <div class="cart-content">
    <% if @cart.cart_items.empty? %>
      <div class="cart-empty">
        <h1>Il tuo carrello è vuoto</h1>
        <br>
        <%= link_to "Aggiungi evento", events_search_path, class: "add-event-link" %>
      </div>
    <% else %>
      <div class="cart-contai">

        <div class="cart-title">
          <h2>Il tuo carrello contiene:</h2>
        </div>

        <div class="cart-main">
          <ul class="cart-list">
            <% @cart.cart_items.each do |cart_elem| %>
              <li class="cart-card">
                <div class="card-border"></div>
                <div class="cart-content">
                  <div class="cart-info">
                    <h3 class="ticket-title"><%= cart_elem.event.title %></h3>
                    <p class="ticket-price"><%= number_to_currency(cart_elem.total_price) %></p>
                  </div>

                  <div class="cart-actions">
                    <%= button_to cart_item_decrease_path(cart_item_id: cart_elem), class: "btn-icon decrease" do %>
                      <i class="fa-solid fa-minus"></i>
                    <% end %>
                    <span class="ticket-quantity"><%= cart_elem.quantity %></span>
                    <%= button_to cart_item_increase_path(cart_item_id: cart_elem), class: "btn-icon increase" do %>
                      <i class="fa-solid fa-plus"></i>
                    <% end %>
                    <%= button_to cart_item_delete_path(cart_item_id: cart_elem.id), method: :delete, class: "delete-link" do %>
                      <i class="fa-solid fa-trash"></i> 
                    <% end %>                
                  </div>
              </li>
            <% end %>
          </ul>
        </div>

        <div class="cart-foot">
          <div class="cart-summary">
            <p class="summary-text">
              <span class="total-text"> Totale: <span class="total-amount"><%= number_to_currency(@cart.sub_total) %></span> </span>
            </p>
          </div>

          <div class="checkout-button">
            <%= button_to checkouts_create_path, data: { turbo: false }, class: "btn proceed-btn" do %>
              Procedi <i class="fa-solid fa-chevron-right"></i>
            <% end %>
          </div>

          <div class="clear-cart">
            <%= button_to "Svuota il carrello", cart_path(@current_cart), method: :delete, class: "btn clear-cart-btn" %>
          </div>
        </div>

      </div>
    <% end %>
  </div>

</div>


<%= render "devise/shared/footer" %>